#!/usr/bin/env ruby
#vim fileencoding=utf-8

require 'curb'
require 'json'
require 'cgi'

req = JSON.load('
%REQ%
')

header = JSON.load('
%HEADER%
')

body = CGI.escape(JSON.load('
%BODY%
').inject([]) do |m, (k,a)|
  a.each {|v| m << "#{k}=#{v}"}; m
end.join("&"))

c = Curl::Easy.new do |curl|
  # curl.ssl_verify_host = false
  curl.url = req["Url"]
  curl.headers = header
  if req["Verb"] == "POST"
    curl.post_body = body
  end
end

# Peform the request
c.http(req["Verb"].upcase)

# What to do when the request succeeds with a 20x response
c.on_success do |c|
  return c.body_str
end
